name: Job Explorer CICD Pipeline

trigger:
  branches:
    include:
      - main
      - develop

variables:
  - name: isMainBranch
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  - name: isDevelopBranch
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/develop')]

jobs:
- job: build_and_deploy_job
  displayName: Build and Deploy Job
  pool:
    vmImage: ubuntu-latest
  variables:
  - group: Azure-Static-Web-Apps-wonderful-glacier-0d6feda0f-variable-group
  
  steps:
  - checkout: self
    submodules: true

  # Deploy to Production (main branch only)
  - task: AzureStaticWebApp@0
    displayName: 'Deploy to Production'
    condition: eq(variables.isMainBranch, 'true')
    inputs:
      azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_WONDERFUL_GLACIER_0D6FEDA0F)
      app_location: "/"
      api_location: ""
      output_location: "dist"

  # Deploy to Develop Environment (develop branch only)
  - task: AzureStaticWebApp@0
    displayName: 'Deploy to Develop Environment'
    condition: eq(variables.isDevelopBranch, 'true')
    inputs:
      azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_WONDERFUL_GLACIER_0D6FEDA0F)
      app_location: "/"
      api_location: ""
      output_location: "dist"
      deployment_environment: "develop"